### ISSUE TITLE
Hotfix for SGS replacement issue

### ISSUE THREAD

**Issue by benny-n** [sogrim/technion-sogrim#214]

**Comment by liadaram1** [comment]
The issue is more difficult that we thought.
We have an invariant that each course belongs to only one `CourseBank`.
However, in Computer Engineer itinerary there could be a course which belongs to "רשימות ליבה" and to "קבוצות התמחות".
As a result, the following scenario happens:
We classify the course as "רשימות ליבה".
The student modifies the course to be "קבוצות התמחות".

Now, the problem begins when we have replacements involved.
let's say we have course A which is a replacement to course B, and course B can be either "רשימות ליבה" or "קבוצות התמחות".
Now the student modifies A (the course he took) as "קבוצות התמחות", but we have no way to determine it is a replacement for B, because A is not even in the original list of "קבוצות התמחות".
So we get A as it is, and thus don't classify it in any "קבוצת התמחות".
